parameters:
    delivery_service_url: 'http://127.0.0.1:8004' # URL du microservice delivery

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'

    # Définition explicite à placer APRÈS le bloc App\
    App\Services\TicketDeliveryService:
        arguments:
            $deliveryServiceUrl: '%delivery_service_url%'
